# Flutter-related parameters:
# The Flutter SDK home location
flutter.sdk=/Users/YOUR_USERNAME/flutter
# or on Windows:
# flutter.sdk=C:\\flutter

# The Flutter engine repo URL, may be overridden by local file.
# flutter.engine.repo.url=https://github.com/flutter/engine/wiki/Setting-up-the-Engine-development-environment

# System architecture to build apps for.
# android.useDeprecatedNdk=true
# flutter.targetPlatform=android-arm

# The Java version to use when compiling the app
org.gradle.jvmargs=-Xmx4096m
